Blogs/urls.py
from django.urls import path
from .views import * 
app_name = 'Blogs'

urlpatterns = [
    path('',blog_list,name='blog_list'),
    path('<int:id>/',blog_detail,name='blog_detail'),
    path('tag/<slug:tag>',blog_tag,name='tag'),
    path('category/<slug:category>',blog_category,name='category')
]

about/urls.py
from django.urls import path
from .views import *
app_name = 'about'

urlpatterns = [
    path('',load,name='load')
]

reservation/urls.py
from django.urls import path
from .views import *
app_name = 'reservation'

urlpatterns = [
    path('',view=reserve,name='reserve')
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foods.urls')),
    path('book/',include('reservation.urls')),
    path('blog/',include('Blogs.urls')),
    path('contacts/',include('contacts.urls')),
    path('stuff/',include('stuff.urls')),
    path('about/',include('about.urls'))
  
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.

def load(request):
    return render (request,'about/templates/about.html')

about/templates/about.html
{% extends "templates/partials/base.html" %}
	{% block content %}
		<!-- Start About -->
	<div class="about-section-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<img src="images/about-img.jpg" alt="" class="img-fluid">
				</div>
				<div class="col-lg-6 col-md-6 text-center">
					<div class="inner-column">
						<h1>Welcome To <span>about</span></h1>
						<h4>درباره سازنده</h4>
						<p>سلام من علیرضا هاشمی هستم و تو مدت 25 روز و 170 ساعت بالاخره تونستم اولین سایتم رو به اتمام برسونم </p>
						<p>و حالا سایت اماده ی لانچ شدن هستش</p>
						<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reserve' %}">Reservation</a>
					</div>
				</div>
				<div class="col-md-12">
					<div class="inner-pt">
						<p>Sed tincidunt, neque at egestas imperdiet, nulla sapien blandit nunc, sit amet pulvinar orci nibh ut massa. Proin nec lectus sed nunc placerat semper. Duis hendrerit elit nec sapien porttitor, ut pretium ipsum feugiat. Aenean volutpat porta nisi in gravida. Curabitur pulvinar ligula sed facilisis bibendum. Nullam vitae nulla elit. </p>
						<p>Integer purus velit, eleifend eu magna volutpat, porttitor blandit lectus. Aenean risus odio, efficitur quis erat eget, mattis tristique arcu. Fusce in ante enim. Integer consectetur elit nec laoreet rutrum. Mauris porta turpis nec tellus accumsan pellentesque. Morbi non quam tempus, convallis urna in, cursus mauris. </p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End About -->
	
	
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->
	

	{% endblock content %}