Blogs/urls.py
from django.urls import path
from .views import * 
app_name = 'Blogs'

urlpatterns = [
    path('',blog_list,name='blog_list'),
    path('<int:id>/',blog_detail,name='blog_detail'),
    path('tag/<slug:tag>',blog_tag,name='tag'),
    path('category/<slug:category>',blog_category,name='category')
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foods.urls')),
    path('book/',include('reservation.urls')),
    path('blog/',include('Blogs.urls')),
    path('contacts/',include('contacts.urls')),
    path('stuff/',include('stuff.urls')),
    path('about/',include('about.urls'))
  
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=40,verbose_name="عنوان مقاله")
    description = models.CharField(max_length=50,verbose_name="توضیحات")
    content = RichTextField(verbose_name="محتوا")
    created_at = models.DateTimeField(auto_now=False,auto_now_add=True)
    related_user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'images/')
    category = models.ForeignKey("Category",on_delete=models.CASCADE,verbose_name="دسته بندی مقالات",related_name="blogs")
    tags = models.ManyToManyField("Tag",related_name="blogs",verbose_name="تگ ها",blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"


class Category(models.Model):
    title = models.CharField(max_length=40,verbose_name="عنوان دسته بندی")
    slug = models.SlugField(verbose_name="نام اصلی")
    status = models.BooleanField(verbose_name="نشان داده بشود؟")
    published_at = models.DateField(auto_now=False , auto_now_add=True)

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی  ها"

    def __str__(self):
        return self.title
    

class Tag(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(verbose_name="نام اصلی")
    published_at = models.DateTimeField(auto_now=False,auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,auto_now_add=False)

    class Meta:
        verbose_name = "تگ"
        verbose_name_plural = "تگ ها"

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey("Blog",verbose_name="مقاله مربوطه",on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=50,verbose_name="نام و نام خانوادگی")
    email = models.EmailField(max_length=50,verbose_name="نشانی  الکترونیکی")
    message = models.TextField(verbose_name="متن پیام")
    date = models.DateField(auto_now=False,auto_now_add=True,verbose_name="تاریخ")

    def __str__(self):
        return self.email


    

Blogs/forms.py
from django import forms
from . models import *

class CommentForm(forms.Form):
    name = forms.CharField(max_length=50 ,required=True)
    email = forms.EmailField(max_length=70 , required=True)
    message = forms.CharField(widget=forms.Textarea)

Blogs/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.core.paginator import Paginator
# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 2) # Show 2 Blogs per page.
    page_number = request.GET.get('page')
    blog_list = paginator.get_page(page_number)
    context = {
        'blog_list':blog_list
    }
    return render(request,'Blogs/templates/blog_list.html',context)


def blog_detail(request , id):
    blog = Blog.objects.get(id = id)
    tags = Tag.objects.all().filter(blogs = blog)
    recents = Blog.objects.all().order_by("-created_at")[:2]
    categories = Category.objects.all()
    comments = Comment.objects.all().filter(blog = blog)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data["name"]
            new_email = form.cleaned_data["email"]
            new_message = form.cleaned_data["message"]

            new_comment = Comment(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()
            
    context = {
        'blog':blog,
        'tags':tags,
        'recents': recents,
        'categories': categories,
        'comments':comments ,
    }
    return render(request,'Blogs/templates/blog_detail.html',context)


def blog_tag(request , tag):

    blogs = Blog.objects.filter(tags__slug = tag)

    context = {
        'blogs':blogs
    }
    return render(request,'Blogs/templates/blog_list.html',context)


def blog_category(request , category):
    blogs = Blog.objects.filter(category__slug = category)

    context = {
        'blogs':blogs
    }
    return render(request,'Blogs/templates/blog_list.html',context)

Blogs/templates/blog_detail.html
{% extends "templates/partials/base.html" %}
{% block content %}

	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>{{blog.title}}</h2>
						<p>{{blog.description}}</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid" src={{blog.image.url}} alt="">							
								<div class="date-blog-up">
									1
								</div>
							</div>
							<div class="inner-blog-detail details-page" >
								<h3 >{{blog.description}}</h3>
								<ul>
									<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.related_user}}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at | date:"Y  M"}}</span></li>
								</ul>
								<p>{{blog.content}}</p>
								<p></p>
								<blockquote>
									<p></p>
								</blockquote>
								<p></p>
							</div>
						</div>
						<div class="blog-comment-box">
							<h3>Comments</h3>
						{% for cm in comments %}
														<div class="comment-item-right">
									<div class="pull-left">
										<a href="#">{{cm.name}}</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{cm.date | date:"Y  M"}}</span>
									</div>
									<div class="des-l">
										<p>{{cm.message}}</p>
									</div>
									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
								</div>
						{% endfor %}
					

						</div>
						<div class="comment-respond-box">
							<h3>Leave your comment </h3>
							<div class="comment-respond-form">
								<form id="commentrespondform" class="comment-form-respond row" method="post">
									{% csrf_token %}
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
										</div>
										<div class="form-group">
											<input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<textarea class="form-control" name="message" id="textarea_com" placeholder="Your Message" rows="2"></textarea>
										</div>
									</div>
									<div class="col-lg-12 col-md-12 col-sm-12">
										<button class="btn btn-submit">Submit comment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			
				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
					<div class="right-side-blog">
						<h3>Search</h3>
						<div class="blog-search-form">
							<input name="search" placeholder="Search blog" type="text">
							<button class="search-btn">
								<i class="fa fa-search" aria-hidden="true"></i>
							</button>
						</div>
						<h3>Categories</h3>
						<div class="blog-categories">
							<ul>
							{% for cat in categories %}
								<li><a href="{% url 'Blogs:category' cat.slug %}"><span>{{cat.title}}</span></a></li>
							{% endfor %}
							

							</ul>
						</div>
						<h3>Recent Post</h3>
						<div class="post-box-blog">
							<div class="recent-post-box">
						{% for blog  in recents  %}
								<div class="recent-box-blog">
									<div class="recent-img">
										<img class="img-fluid" src={{blog.image.url}} alt="">
									</div>
									<div class="recent-info">
										<ul>
											<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.related_user}}</span></li>
											<li>|</li>
											<li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at | date:"Y  M"}}</span></li>
										</ul>
										<h4>{{blog.description}}</h4>
									</div>
								</div>
						{% endfor %}

									<div class="recent-img">
										<img class="img-fluid" src="images/post-img-01.jpg" alt="">
									</div>

								</div>
							</div>
						</div>
						<h3>Recent Tag</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
                            {% for tag in tags  %}
							 <li class="list-inline-item"><a href="{% url 'Blogs:tag' tag.slug %}">{{tag.title}}</a></li>
							{% endfor %}
							
								

							</ul>
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</div>
	<!-- End details -->
	
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->
	

{% endblock content %}
	

Blogs/templates/blog_list.html
{% extends "templates/partials/base.html" %}

{% block content %}
<html>

	
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Blog</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
{% for blog in blog_list %}
				<div class="col-lg-4 col-md-6 col-12" dir="rtl" >
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="{{blog.image.url}}" style=height:360px; alt="">
						</div>
						<div  class="blog-detail" >
							<h4>{{blog.title}}</h4>
							<ul>
								<li><span>Post by {{blog.related_user}}</span></li>
								<li></li>
								<li><span>{{blog.created_at | date:"Y  M"}}</span></li>
							</ul>
							<p>{{blog.content | truncatewords:30}} </p>
							<p> </p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'Blogs:blog_detail' blog.id %}">Read More</a>
						</div>
					</div>
				</div>
{% endfor %}


				</div>
			</div>
		</div>
	</div>
	<!-- End blog -->

{% if blog_list.has_other_pages  %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if blog_list.has_previous %}
	
	<li class="page-item">
      <a class="page-link" href="?page={{blog_list.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
	{% endif %}
  {% for page in blog_list.paginator.page_range %}
  {% if blog_list.number == page %}
   <li class="page-item active" ><a class="page-link" href="?page={{page}}">{{page}}</a></li>
  {% else %} <li class="page-item " ><a class="page-link" href="?page={{page}}">{{page}}</a></li>
  {% endif %}
   

  {% endfor %}

  {% if blog_list.has_next %}
  
    <li class="page-item">
      <a class="page-link" href="?page={{blog_list.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  {% endif %}
  </ul>
</nav>


{% endif %}

<!-- end-paginator--! >




	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->
	

</html>
{% endblock content %}